# Generated by Django 4.0.6 on 2023-04-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
