# Generated by Django 3.2.12 on 2023-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('09:00 AM', '09:00 : 09:30'), ('10:00 AM', '10:00 : 10:30'), ('11:00 AM', '11:00 : 11:30'), ('12:00 PM', '12:00 : 12:30'), ('1:00 PM', '13:00 : 13:30'), ('2:00 PM', '14:00 : 14:30'), ('3:00 PM', '15:00 : 15:30'), ('4:00 PM', '16:00 : 16:30'), ('15:00 PM', '17:00 : 17:30')], max_length=200),
        ),
    ]
