# Generated by Django 3.2.12 on 2023-04-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230416_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specality',
            new_name='speciality',
        ),
    ]
