# Generated by Django 3.2.12 on 2023-04-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_specality_doctor_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='days',
            new_name='day',
        ),
    ]
